<?php
/**
 * MediaThumbnailApi
 * PHP version 5
 *
 * @category Class
 * @package  Shopware6SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Management API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.15
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Shopware6SDK\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Shopware6SDK\ApiException;
use Shopware6SDK\Configuration;
use Shopware6SDK\HeaderSelector;
use Shopware6SDK\ObjectSerializer;

/**
 * MediaThumbnailApi Class Doc Comment
 *
 * @category Class
 * @package  Shopware6SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MediaThumbnailApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createMediaThumbnail
     *
     * Create a new Media Thumbnail resources
     *
     * @param  \Shopware6SDK\Model\Body80 $body body (optional)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \Shopware6SDK\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Shopware6SDK\Model\InlineResponse200123
     */
    public function createMediaThumbnail($body = null, $_response = null)
    {
        list($response) = $this->createMediaThumbnailWithHttpInfo($body, $_response);
        return $response;
    }

    /**
     * Operation createMediaThumbnailWithHttpInfo
     *
     * Create a new Media Thumbnail resources
     *
     * @param  \Shopware6SDK\Model\Body80 $body (optional)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \Shopware6SDK\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Shopware6SDK\Model\InlineResponse200123, HTTP status code, HTTP response headers (array of strings)
     */
    public function createMediaThumbnailWithHttpInfo($body = null, $_response = null)
    {
        $returnType = '\Shopware6SDK\Model\InlineResponse200123';
        $request = $this->createMediaThumbnailRequest($body, $_response);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Shopware6SDK\Model\InlineResponse200123',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createMediaThumbnailAsync
     *
     * Create a new Media Thumbnail resources
     *
     * @param  \Shopware6SDK\Model\Body80 $body (optional)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createMediaThumbnailAsync($body = null, $_response = null)
    {
        return $this->createMediaThumbnailAsyncWithHttpInfo($body, $_response)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createMediaThumbnailAsyncWithHttpInfo
     *
     * Create a new Media Thumbnail resources
     *
     * @param  \Shopware6SDK\Model\Body80 $body (optional)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createMediaThumbnailAsyncWithHttpInfo($body = null, $_response = null)
    {
        $returnType = '\Shopware6SDK\Model\InlineResponse200123';
        $request = $this->createMediaThumbnailRequest($body, $_response);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createMediaThumbnail'
     *
     * @param  \Shopware6SDK\Model\Body80 $body (optional)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function createMediaThumbnailRequest($body = null, $_response = null)
    {

        $resourcePath = '/media-thumbnail';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($_response !== null) {
            $queryParams['_response'] = ObjectSerializer::toQueryValue($_response);
        }


        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/vnd.api+json', 'application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/vnd.api+json', 'application/json'],
                ['application/vnd.api+json', 'application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation createMediaThumbnail
     *
     * Create a new Media Thumbnail resources
     *
     * @param  \Shopware6SDK\Model\MediaThumbnailFlat $body body (optional)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \Shopware6SDK\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Shopware6SDK\Model\InlineResponse200123
     */
    public function createMediaThumbnail($body = null, $_response = null)
    {
        list($response) = $this->createMediaThumbnailWithHttpInfo($body, $_response);
        return $response;
    }

    /**
     * Operation createMediaThumbnailWithHttpInfo
     *
     * Create a new Media Thumbnail resources
     *
     * @param  \Shopware6SDK\Model\MediaThumbnailFlat $body (optional)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \Shopware6SDK\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Shopware6SDK\Model\InlineResponse200123, HTTP status code, HTTP response headers (array of strings)
     */
    public function createMediaThumbnailWithHttpInfo($body = null, $_response = null)
    {
        $returnType = '\Shopware6SDK\Model\InlineResponse200123';
        $request = $this->createMediaThumbnailRequest($body, $_response);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Shopware6SDK\Model\InlineResponse200123',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createMediaThumbnailAsync
     *
     * Create a new Media Thumbnail resources
     *
     * @param  \Shopware6SDK\Model\MediaThumbnailFlat $body (optional)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createMediaThumbnailAsync($body = null, $_response = null)
    {
        return $this->createMediaThumbnailAsyncWithHttpInfo($body, $_response)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createMediaThumbnailAsyncWithHttpInfo
     *
     * Create a new Media Thumbnail resources
     *
     * @param  \Shopware6SDK\Model\MediaThumbnailFlat $body (optional)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createMediaThumbnailAsyncWithHttpInfo($body = null, $_response = null)
    {
        $returnType = '\Shopware6SDK\Model\InlineResponse200123';
        $request = $this->createMediaThumbnailRequest($body, $_response);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createMediaThumbnail'
     *
     * @param  \Shopware6SDK\Model\MediaThumbnailFlat $body (optional)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function createMediaThumbnailRequest($body = null, $_response = null)
    {

        $resourcePath = '/media-thumbnail';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($_response !== null) {
            $queryParams['_response'] = ObjectSerializer::toQueryValue($_response);
        }


        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/vnd.api+json', 'application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/vnd.api+json', 'application/json'],
                ['application/vnd.api+json', 'application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteMediaThumbnail
     *
     * Delete a Media Thumbnail resource
     *
     * @param  string $id Identifier for the media_thumbnail (required)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \Shopware6SDK\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function deleteMediaThumbnail($id, $_response = null)
    {
        $this->deleteMediaThumbnailWithHttpInfo($id, $_response);
    }

    /**
     * Operation deleteMediaThumbnailWithHttpInfo
     *
     * Delete a Media Thumbnail resource
     *
     * @param  string $id Identifier for the media_thumbnail (required)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \Shopware6SDK\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteMediaThumbnailWithHttpInfo($id, $_response = null)
    {
        $returnType = '';
        $request = $this->deleteMediaThumbnailRequest($id, $_response);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation deleteMediaThumbnailAsync
     *
     * Delete a Media Thumbnail resource
     *
     * @param  string $id Identifier for the media_thumbnail (required)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteMediaThumbnailAsync($id, $_response = null)
    {
        return $this->deleteMediaThumbnailAsyncWithHttpInfo($id, $_response)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteMediaThumbnailAsyncWithHttpInfo
     *
     * Delete a Media Thumbnail resource
     *
     * @param  string $id Identifier for the media_thumbnail (required)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteMediaThumbnailAsyncWithHttpInfo($id, $_response = null)
    {
        $returnType = '';
        $request = $this->deleteMediaThumbnailRequest($id, $_response);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteMediaThumbnail'
     *
     * @param  string $id Identifier for the media_thumbnail (required)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function deleteMediaThumbnailRequest($id, $_response = null)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling deleteMediaThumbnail'
            );
        }

        $resourcePath = '/media-thumbnail/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($_response !== null) {
            $queryParams['_response'] = ObjectSerializer::toQueryValue($_response);
        }

        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/vnd.api+json', 'application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/vnd.api+json', 'application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getMediaThumbnail
     *
     * Detailed information about a Media Thumbnail resource
     *
     * @param  string $id Identifier for the media_thumbnail (required)
     *
     * @throws \Shopware6SDK\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Shopware6SDK\Model\InlineResponse200123
     */
    public function getMediaThumbnail($id)
    {
        list($response) = $this->getMediaThumbnailWithHttpInfo($id);
        return $response;
    }

    /**
     * Operation getMediaThumbnailWithHttpInfo
     *
     * Detailed information about a Media Thumbnail resource
     *
     * @param  string $id Identifier for the media_thumbnail (required)
     *
     * @throws \Shopware6SDK\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Shopware6SDK\Model\InlineResponse200123, HTTP status code, HTTP response headers (array of strings)
     */
    public function getMediaThumbnailWithHttpInfo($id)
    {
        $returnType = '\Shopware6SDK\Model\InlineResponse200123';
        $request = $this->getMediaThumbnailRequest($id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Shopware6SDK\Model\InlineResponse200123',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getMediaThumbnailAsync
     *
     * Detailed information about a Media Thumbnail resource
     *
     * @param  string $id Identifier for the media_thumbnail (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getMediaThumbnailAsync($id)
    {
        return $this->getMediaThumbnailAsyncWithHttpInfo($id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getMediaThumbnailAsyncWithHttpInfo
     *
     * Detailed information about a Media Thumbnail resource
     *
     * @param  string $id Identifier for the media_thumbnail (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getMediaThumbnailAsyncWithHttpInfo($id)
    {
        $returnType = '\Shopware6SDK\Model\InlineResponse200123';
        $request = $this->getMediaThumbnailRequest($id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getMediaThumbnail'
     *
     * @param  string $id Identifier for the media_thumbnail (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getMediaThumbnailRequest($id)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling getMediaThumbnail'
            );
        }

        $resourcePath = '/media-thumbnail/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/vnd.api+json', 'application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/vnd.api+json', 'application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getMediaThumbnailList
     *
     * List with basic information of Media Thumbnail resources
     *
     * @param  int $limit Max amount of resources to be returned in a page (optional)
     * @param  int $page The page to be returned (optional)
     * @param  string $query Encoded SwagQL in JSON (optional)
     *
     * @throws \Shopware6SDK\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Shopware6SDK\Model\InlineResponse200121
     */
    public function getMediaThumbnailList($limit = null, $page = null, $query = null)
    {
        list($response) = $this->getMediaThumbnailListWithHttpInfo($limit, $page, $query);
        return $response;
    }

    /**
     * Operation getMediaThumbnailListWithHttpInfo
     *
     * List with basic information of Media Thumbnail resources
     *
     * @param  int $limit Max amount of resources to be returned in a page (optional)
     * @param  int $page The page to be returned (optional)
     * @param  string $query Encoded SwagQL in JSON (optional)
     *
     * @throws \Shopware6SDK\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Shopware6SDK\Model\InlineResponse200121, HTTP status code, HTTP response headers (array of strings)
     */
    public function getMediaThumbnailListWithHttpInfo($limit = null, $page = null, $query = null)
    {
        $returnType = '\Shopware6SDK\Model\InlineResponse200121';
        $request = $this->getMediaThumbnailListRequest($limit, $page, $query);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Shopware6SDK\Model\InlineResponse200121',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getMediaThumbnailListAsync
     *
     * List with basic information of Media Thumbnail resources
     *
     * @param  int $limit Max amount of resources to be returned in a page (optional)
     * @param  int $page The page to be returned (optional)
     * @param  string $query Encoded SwagQL in JSON (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getMediaThumbnailListAsync($limit = null, $page = null, $query = null)
    {
        return $this->getMediaThumbnailListAsyncWithHttpInfo($limit, $page, $query)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getMediaThumbnailListAsyncWithHttpInfo
     *
     * List with basic information of Media Thumbnail resources
     *
     * @param  int $limit Max amount of resources to be returned in a page (optional)
     * @param  int $page The page to be returned (optional)
     * @param  string $query Encoded SwagQL in JSON (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getMediaThumbnailListAsyncWithHttpInfo($limit = null, $page = null, $query = null)
    {
        $returnType = '\Shopware6SDK\Model\InlineResponse200121';
        $request = $this->getMediaThumbnailListRequest($limit, $page, $query);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getMediaThumbnailList'
     *
     * @param  int $limit Max amount of resources to be returned in a page (optional)
     * @param  int $page The page to be returned (optional)
     * @param  string $query Encoded SwagQL in JSON (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getMediaThumbnailListRequest($limit = null, $page = null, $query = null)
    {

        $resourcePath = '/media-thumbnail';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($limit !== null) {
            $queryParams['limit'] = ObjectSerializer::toQueryValue($limit);
        }
        // query params
        if ($page !== null) {
            $queryParams['page'] = ObjectSerializer::toQueryValue($page);
        }
        // query params
        if ($query !== null) {
            $queryParams['query'] = ObjectSerializer::toQueryValue($query);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/vnd.api+json', 'application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/vnd.api+json', 'application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateMediaThumbnail
     *
     * Partially update information about a Media Thumbnail resource
     *
     * @param  string $id Identifier for the media_thumbnail (required)
     * @param  \Shopware6SDK\Model\Body81 $body Partially update information about a Media Thumbnail resource. (optional)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \Shopware6SDK\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Shopware6SDK\Model\InlineResponse200123
     */
    public function updateMediaThumbnail($id, $body = null, $_response = null)
    {
        list($response) = $this->updateMediaThumbnailWithHttpInfo($id, $body, $_response);
        return $response;
    }

    /**
     * Operation updateMediaThumbnailWithHttpInfo
     *
     * Partially update information about a Media Thumbnail resource
     *
     * @param  string $id Identifier for the media_thumbnail (required)
     * @param  \Shopware6SDK\Model\Body81 $body Partially update information about a Media Thumbnail resource. (optional)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \Shopware6SDK\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Shopware6SDK\Model\InlineResponse200123, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateMediaThumbnailWithHttpInfo($id, $body = null, $_response = null)
    {
        $returnType = '\Shopware6SDK\Model\InlineResponse200123';
        $request = $this->updateMediaThumbnailRequest($id, $body, $_response);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Shopware6SDK\Model\InlineResponse200123',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation updateMediaThumbnailAsync
     *
     * Partially update information about a Media Thumbnail resource
     *
     * @param  string $id Identifier for the media_thumbnail (required)
     * @param  \Shopware6SDK\Model\Body81 $body Partially update information about a Media Thumbnail resource. (optional)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateMediaThumbnailAsync($id, $body = null, $_response = null)
    {
        return $this->updateMediaThumbnailAsyncWithHttpInfo($id, $body, $_response)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateMediaThumbnailAsyncWithHttpInfo
     *
     * Partially update information about a Media Thumbnail resource
     *
     * @param  string $id Identifier for the media_thumbnail (required)
     * @param  \Shopware6SDK\Model\Body81 $body Partially update information about a Media Thumbnail resource. (optional)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateMediaThumbnailAsyncWithHttpInfo($id, $body = null, $_response = null)
    {
        $returnType = '\Shopware6SDK\Model\InlineResponse200123';
        $request = $this->updateMediaThumbnailRequest($id, $body, $_response);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateMediaThumbnail'
     *
     * @param  string $id Identifier for the media_thumbnail (required)
     * @param  \Shopware6SDK\Model\Body81 $body Partially update information about a Media Thumbnail resource. (optional)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function updateMediaThumbnailRequest($id, $body = null, $_response = null)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling updateMediaThumbnail'
            );
        }

        $resourcePath = '/media-thumbnail/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($_response !== null) {
            $queryParams['_response'] = ObjectSerializer::toQueryValue($_response);
        }

        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/vnd.api+json', 'application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/vnd.api+json', 'application/json'],
                ['application/vnd.api+json', 'application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PATCH',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateMediaThumbnail
     *
     * Partially update information about a Media Thumbnail resource
     *
     * @param  string $id Identifier for the media_thumbnail (required)
     * @param  \Shopware6SDK\Model\MediaThumbnailFlat $body Partially update information about a Media Thumbnail resource. (optional)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \Shopware6SDK\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Shopware6SDK\Model\InlineResponse200123
     */
    public function updateMediaThumbnail($id, $body = null, $_response = null)
    {
        list($response) = $this->updateMediaThumbnailWithHttpInfo($id, $body, $_response);
        return $response;
    }

    /**
     * Operation updateMediaThumbnailWithHttpInfo
     *
     * Partially update information about a Media Thumbnail resource
     *
     * @param  string $id Identifier for the media_thumbnail (required)
     * @param  \Shopware6SDK\Model\MediaThumbnailFlat $body Partially update information about a Media Thumbnail resource. (optional)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \Shopware6SDK\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Shopware6SDK\Model\InlineResponse200123, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateMediaThumbnailWithHttpInfo($id, $body = null, $_response = null)
    {
        $returnType = '\Shopware6SDK\Model\InlineResponse200123';
        $request = $this->updateMediaThumbnailRequest($id, $body, $_response);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Shopware6SDK\Model\InlineResponse200123',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation updateMediaThumbnailAsync
     *
     * Partially update information about a Media Thumbnail resource
     *
     * @param  string $id Identifier for the media_thumbnail (required)
     * @param  \Shopware6SDK\Model\MediaThumbnailFlat $body Partially update information about a Media Thumbnail resource. (optional)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateMediaThumbnailAsync($id, $body = null, $_response = null)
    {
        return $this->updateMediaThumbnailAsyncWithHttpInfo($id, $body, $_response)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateMediaThumbnailAsyncWithHttpInfo
     *
     * Partially update information about a Media Thumbnail resource
     *
     * @param  string $id Identifier for the media_thumbnail (required)
     * @param  \Shopware6SDK\Model\MediaThumbnailFlat $body Partially update information about a Media Thumbnail resource. (optional)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateMediaThumbnailAsyncWithHttpInfo($id, $body = null, $_response = null)
    {
        $returnType = '\Shopware6SDK\Model\InlineResponse200123';
        $request = $this->updateMediaThumbnailRequest($id, $body, $_response);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateMediaThumbnail'
     *
     * @param  string $id Identifier for the media_thumbnail (required)
     * @param  \Shopware6SDK\Model\MediaThumbnailFlat $body Partially update information about a Media Thumbnail resource. (optional)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function updateMediaThumbnailRequest($id, $body = null, $_response = null)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling updateMediaThumbnail'
            );
        }

        $resourcePath = '/media-thumbnail/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($_response !== null) {
            $queryParams['_response'] = ObjectSerializer::toQueryValue($_response);
        }

        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/vnd.api+json', 'application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/vnd.api+json', 'application/json'],
                ['application/vnd.api+json', 'application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PATCH',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
