<?php
/**
 * UserRelationships
 *
 * PHP version 5
 *
 * @category Class
 * @package  Shopware6SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Management API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.15
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Shopware6SDK\Model;

use \ArrayAccess;
use \Shopware6SDK\ObjectSerializer;

/**
 * UserRelationships Class Doc Comment
 *
 * @category Class
 * @package  Shopware6SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UserRelationships implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'user_relationships';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'locale' => '\Shopware6SDK\Model\UserRelationshipsLocale',
'avatar_media' => '\Shopware6SDK\Model\UserRelationshipsAvatarMedia',
'media' => '\Shopware6SDK\Model\UserRelationshipsMedia',
'access_keys' => '\Shopware6SDK\Model\UserRelationshipsAccessKeys',
'state_machine_history_entries' => '\Shopware6SDK\Model\UserRelationshipsStateMachineHistoryEntries',
'import_export_log_entries' => '\Shopware6SDK\Model\UserRelationshipsImportExportLogEntries',
'acl_roles' => '\Shopware6SDK\Model\UserRelationshipsAclRoles',
'recovery_user' => '\Shopware6SDK\Model\UserRelationshipsRecoveryUser'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'locale' => null,
'avatar_media' => null,
'media' => null,
'access_keys' => null,
'state_machine_history_entries' => null,
'import_export_log_entries' => null,
'acl_roles' => null,
'recovery_user' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'locale' => 'locale',
'avatar_media' => 'avatarMedia',
'media' => 'media',
'access_keys' => 'accessKeys',
'state_machine_history_entries' => 'stateMachineHistoryEntries',
'import_export_log_entries' => 'importExportLogEntries',
'acl_roles' => 'aclRoles',
'recovery_user' => 'recoveryUser'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'locale' => 'setLocale',
'avatar_media' => 'setAvatarMedia',
'media' => 'setMedia',
'access_keys' => 'setAccessKeys',
'state_machine_history_entries' => 'setStateMachineHistoryEntries',
'import_export_log_entries' => 'setImportExportLogEntries',
'acl_roles' => 'setAclRoles',
'recovery_user' => 'setRecoveryUser'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'locale' => 'getLocale',
'avatar_media' => 'getAvatarMedia',
'media' => 'getMedia',
'access_keys' => 'getAccessKeys',
'state_machine_history_entries' => 'getStateMachineHistoryEntries',
'import_export_log_entries' => 'getImportExportLogEntries',
'acl_roles' => 'getAclRoles',
'recovery_user' => 'getRecoveryUser'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['locale'] = isset($data['locale']) ? $data['locale'] : null;
        $this->container['avatar_media'] = isset($data['avatar_media']) ? $data['avatar_media'] : null;
        $this->container['media'] = isset($data['media']) ? $data['media'] : null;
        $this->container['access_keys'] = isset($data['access_keys']) ? $data['access_keys'] : null;
        $this->container['state_machine_history_entries'] = isset($data['state_machine_history_entries']) ? $data['state_machine_history_entries'] : null;
        $this->container['import_export_log_entries'] = isset($data['import_export_log_entries']) ? $data['import_export_log_entries'] : null;
        $this->container['acl_roles'] = isset($data['acl_roles']) ? $data['acl_roles'] : null;
        $this->container['recovery_user'] = isset($data['recovery_user']) ? $data['recovery_user'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets locale
     *
     * @return \Shopware6SDK\Model\UserRelationshipsLocale
     */
    public function getLocale()
    {
        return $this->container['locale'];
    }

    /**
     * Sets locale
     *
     * @param \Shopware6SDK\Model\UserRelationshipsLocale $locale locale
     *
     * @return $this
     */
    public function setLocale($locale)
    {
        $this->container['locale'] = $locale;

        return $this;
    }

    /**
     * Gets avatar_media
     *
     * @return \Shopware6SDK\Model\UserRelationshipsAvatarMedia
     */
    public function getAvatarMedia()
    {
        return $this->container['avatar_media'];
    }

    /**
     * Sets avatar_media
     *
     * @param \Shopware6SDK\Model\UserRelationshipsAvatarMedia $avatar_media avatar_media
     *
     * @return $this
     */
    public function setAvatarMedia($avatar_media)
    {
        $this->container['avatar_media'] = $avatar_media;

        return $this;
    }

    /**
     * Gets media
     *
     * @return \Shopware6SDK\Model\UserRelationshipsMedia
     */
    public function getMedia()
    {
        return $this->container['media'];
    }

    /**
     * Sets media
     *
     * @param \Shopware6SDK\Model\UserRelationshipsMedia $media media
     *
     * @return $this
     */
    public function setMedia($media)
    {
        $this->container['media'] = $media;

        return $this;
    }

    /**
     * Gets access_keys
     *
     * @return \Shopware6SDK\Model\UserRelationshipsAccessKeys
     */
    public function getAccessKeys()
    {
        return $this->container['access_keys'];
    }

    /**
     * Sets access_keys
     *
     * @param \Shopware6SDK\Model\UserRelationshipsAccessKeys $access_keys access_keys
     *
     * @return $this
     */
    public function setAccessKeys($access_keys)
    {
        $this->container['access_keys'] = $access_keys;

        return $this;
    }

    /**
     * Gets state_machine_history_entries
     *
     * @return \Shopware6SDK\Model\UserRelationshipsStateMachineHistoryEntries
     */
    public function getStateMachineHistoryEntries()
    {
        return $this->container['state_machine_history_entries'];
    }

    /**
     * Sets state_machine_history_entries
     *
     * @param \Shopware6SDK\Model\UserRelationshipsStateMachineHistoryEntries $state_machine_history_entries state_machine_history_entries
     *
     * @return $this
     */
    public function setStateMachineHistoryEntries($state_machine_history_entries)
    {
        $this->container['state_machine_history_entries'] = $state_machine_history_entries;

        return $this;
    }

    /**
     * Gets import_export_log_entries
     *
     * @return \Shopware6SDK\Model\UserRelationshipsImportExportLogEntries
     */
    public function getImportExportLogEntries()
    {
        return $this->container['import_export_log_entries'];
    }

    /**
     * Sets import_export_log_entries
     *
     * @param \Shopware6SDK\Model\UserRelationshipsImportExportLogEntries $import_export_log_entries import_export_log_entries
     *
     * @return $this
     */
    public function setImportExportLogEntries($import_export_log_entries)
    {
        $this->container['import_export_log_entries'] = $import_export_log_entries;

        return $this;
    }

    /**
     * Gets acl_roles
     *
     * @return \Shopware6SDK\Model\UserRelationshipsAclRoles
     */
    public function getAclRoles()
    {
        return $this->container['acl_roles'];
    }

    /**
     * Sets acl_roles
     *
     * @param \Shopware6SDK\Model\UserRelationshipsAclRoles $acl_roles acl_roles
     *
     * @return $this
     */
    public function setAclRoles($acl_roles)
    {
        $this->container['acl_roles'] = $acl_roles;

        return $this;
    }

    /**
     * Gets recovery_user
     *
     * @return \Shopware6SDK\Model\UserRelationshipsRecoveryUser
     */
    public function getRecoveryUser()
    {
        return $this->container['recovery_user'];
    }

    /**
     * Sets recovery_user
     *
     * @param \Shopware6SDK\Model\UserRelationshipsRecoveryUser $recovery_user recovery_user
     *
     * @return $this
     */
    public function setRecoveryUser($recovery_user)
    {
        $this->container['recovery_user'] = $recovery_user;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
