<?php
/**
 * DocumentBaseConfigAttributesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ShopwareSDK6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Management API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.15
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ShopwareSDK6;

/**
 * DocumentBaseConfigAttributesTest Class Doc Comment
 *
 * @category    Class
 * @description DocumentBaseConfigAttributes
 * @package     ShopwareSDK6
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DocumentBaseConfigAttributesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DocumentBaseConfigAttributes"
     */
    public function testDocumentBaseConfigAttributes()
    {
    }

    /**
     * Test attribute "document_type_id"
     */
    public function testPropertyDocumentTypeId()
    {
    }

    /**
     * Test attribute "logo_id"
     */
    public function testPropertyLogoId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "filename_prefix"
     */
    public function testPropertyFilenamePrefix()
    {
    }

    /**
     * Test attribute "filename_suffix"
     */
    public function testPropertyFilenameSuffix()
    {
    }

    /**
     * Test attribute "global"
     */
    public function testPropertyGlobal()
    {
    }

    /**
     * Test attribute "document_number"
     */
    public function testPropertyDocumentNumber()
    {
    }

    /**
     * Test attribute "config"
     */
    public function testPropertyConfig()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }
}
