<?php
/**
 * MediaFolderConfigurationAttributesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Shopware6SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Management API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.15
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Shopware6SDK;

/**
 * MediaFolderConfigurationAttributesTest Class Doc Comment
 *
 * @category    Class
 * @description MediaFolderConfigurationAttributes
 * @package     Shopware6SDK
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MediaFolderConfigurationAttributesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MediaFolderConfigurationAttributes"
     */
    public function testMediaFolderConfigurationAttributes()
    {
    }

    /**
     * Test attribute "create_thumbnails"
     */
    public function testPropertyCreateThumbnails()
    {
    }

    /**
     * Test attribute "keep_aspect_ratio"
     */
    public function testPropertyKeepAspectRatio()
    {
    }

    /**
     * Test attribute "thumbnail_quality"
     */
    public function testPropertyThumbnailQuality()
    {
    }

    /**
     * Test attribute "private"
     */
    public function testPropertyPrivate()
    {
    }

    /**
     * Test attribute "no_association"
     */
    public function testPropertyNoAssociation()
    {
    }

    /**
     * Test attribute "custom_fields"
     */
    public function testPropertyCustomFields()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }
}
