<?php
/**
 * StateMachineStateRelationshipsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Shopware6SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Management API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.15
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Shopware6SDK;

/**
 * StateMachineStateRelationshipsTest Class Doc Comment
 *
 * @category    Class
 * @description StateMachineStateRelationships
 * @package     Shopware6SDK
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StateMachineStateRelationshipsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "StateMachineStateRelationships"
     */
    public function testStateMachineStateRelationships()
    {
    }

    /**
     * Test attribute "state_machine"
     */
    public function testPropertyStateMachine()
    {
    }

    /**
     * Test attribute "from_state_machine_transitions"
     */
    public function testPropertyFromStateMachineTransitions()
    {
    }

    /**
     * Test attribute "to_state_machine_transitions"
     */
    public function testPropertyToStateMachineTransitions()
    {
    }

    /**
     * Test attribute "order_transactions"
     */
    public function testPropertyOrderTransactions()
    {
    }

    /**
     * Test attribute "order_deliveries"
     */
    public function testPropertyOrderDeliveries()
    {
    }

    /**
     * Test attribute "orders"
     */
    public function testPropertyOrders()
    {
    }

    /**
     * Test attribute "to_state_machine_history_entries"
     */
    public function testPropertyToStateMachineHistoryEntries()
    {
    }

    /**
     * Test attribute "from_state_machine_history_entries"
     */
    public function testPropertyFromStateMachineHistoryEntries()
    {
    }
}
