<?php
/**
 * TaxRuleAttributesDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ShopwareSDK6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Management API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.15
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ShopwareSDK6;

/**
 * TaxRuleAttributesDataTest Class Doc Comment
 *
 * @category    Class
 * @description TaxRuleAttributesData
 * @package     ShopwareSDK6
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TaxRuleAttributesDataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TaxRuleAttributesData"
     */
    public function testTaxRuleAttributesData()
    {
    }

    /**
     * Test attribute "states"
     */
    public function testPropertyStates()
    {
    }

    /**
     * Test attribute "zip_code"
     */
    public function testPropertyZipCode()
    {
    }

    /**
     * Test attribute "from_zip_code"
     */
    public function testPropertyFromZipCode()
    {
    }

    /**
     * Test attribute "to_zip_code"
     */
    public function testPropertyToZipCode()
    {
    }
}
