<?php
/**
 * UserRelationshipsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Shopware6SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Management API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.15
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Shopware6SDK;

/**
 * UserRelationshipsTest Class Doc Comment
 *
 * @category    Class
 * @description UserRelationships
 * @package     Shopware6SDK
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UserRelationshipsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UserRelationships"
     */
    public function testUserRelationships()
    {
    }

    /**
     * Test attribute "locale"
     */
    public function testPropertyLocale()
    {
    }

    /**
     * Test attribute "avatar_media"
     */
    public function testPropertyAvatarMedia()
    {
    }

    /**
     * Test attribute "media"
     */
    public function testPropertyMedia()
    {
    }

    /**
     * Test attribute "access_keys"
     */
    public function testPropertyAccessKeys()
    {
    }

    /**
     * Test attribute "state_machine_history_entries"
     */
    public function testPropertyStateMachineHistoryEntries()
    {
    }

    /**
     * Test attribute "import_export_log_entries"
     */
    public function testPropertyImportExportLogEntries()
    {
    }

    /**
     * Test attribute "acl_roles"
     */
    public function testPropertyAclRoles()
    {
    }

    /**
     * Test attribute "recovery_user"
     */
    public function testPropertyRecoveryUser()
    {
    }
}
