<?php
/**
 * CustomerApiTest
 * PHP version 5
 *
 * @category Class
 * @package  ShopwareSDK6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Management API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.15
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace ShopwareSDK6;

use ShopwareSDK6\Configuration;
use ShopwareSDK6\ApiException;
use ShopwareSDK6\ObjectSerializer;

/**
 * CustomerApiTest Class Doc Comment
 *
 * @category Class
 * @package  ShopwareSDK6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CustomerApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createCustomer
     *
     * Create a new Customer resources.
     *
     */
    public function testCreateCustomer()
    {
    }

    /**
     * Test case for deleteCustomer
     *
     * Delete a Customer resource.
     *
     */
    public function testDeleteCustomer()
    {
    }

    /**
     * Test case for getCustomer
     *
     * Detailed information about a Customer resource.
     *
     */
    public function testGetCustomer()
    {
    }

    /**
     * Test case for getCustomerList
     *
     * List with basic information of Customer resources.
     *
     */
    public function testGetCustomerList()
    {
    }

    /**
     * Test case for updateCustomer
     *
     * Partially update information about a Customer resource.
     *
     */
    public function testUpdateCustomer()
    {
    }
}
