<?php
/**
 * MessageQueueStatsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Shopware6SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Management API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.15
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Shopware6SDK;

use Shopware6SDK\Configuration;
use Shopware6SDK\ApiException;
use Shopware6SDK\ObjectSerializer;

/**
 * MessageQueueStatsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Shopware6SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MessageQueueStatsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createMessageQueueStats
     *
     * Create a new Message Queue Stats resources.
     *
     */
    public function testCreateMessageQueueStats()
    {
    }

    /**
     * Test case for deleteMessageQueueStats
     *
     * Delete a Message Queue Stats resource.
     *
     */
    public function testDeleteMessageQueueStats()
    {
    }

    /**
     * Test case for getMessageQueueStats
     *
     * Detailed information about a Message Queue Stats resource.
     *
     */
    public function testGetMessageQueueStats()
    {
    }

    /**
     * Test case for getMessageQueueStatsList
     *
     * List with basic information of Message Queue Stats resources.
     *
     */
    public function testGetMessageQueueStatsList()
    {
    }

    /**
     * Test case for updateMessageQueueStats
     *
     * Partially update information about a Message Queue Stats resource.
     *
     */
    public function testUpdateMessageQueueStats()
    {
    }
}
