<?php
/**
 * NumberRangeApiTest
 * PHP version 5
 *
 * @category Class
 * @package  ShopwareSDK6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Management API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.15
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace ShopwareSDK6;

use ShopwareSDK6\Configuration;
use ShopwareSDK6\ApiException;
use ShopwareSDK6\ObjectSerializer;

/**
 * NumberRangeApiTest Class Doc Comment
 *
 * @category Class
 * @package  ShopwareSDK6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class NumberRangeApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createNumberRange
     *
     * Create a new Number Range resources.
     *
     */
    public function testCreateNumberRange()
    {
    }

    /**
     * Test case for deleteNumberRange
     *
     * Delete a Number Range resource.
     *
     */
    public function testDeleteNumberRange()
    {
    }

    /**
     * Test case for getNumberRange
     *
     * Detailed information about a Number Range resource.
     *
     */
    public function testGetNumberRange()
    {
    }

    /**
     * Test case for getNumberRangeList
     *
     * List with basic information of Number Range resources.
     *
     */
    public function testGetNumberRangeList()
    {
    }

    /**
     * Test case for updateNumberRange
     *
     * Partially update information about a Number Range resource.
     *
     */
    public function testUpdateNumberRange()
    {
    }
}
