<?php
/**
 * OrderLineItemApiTest
 * PHP version 5
 *
 * @category Class
 * @package  ShopwareSDK6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Management API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.15
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace ShopwareSDK6;

use ShopwareSDK6\Configuration;
use ShopwareSDK6\ApiException;
use ShopwareSDK6\ObjectSerializer;

/**
 * OrderLineItemApiTest Class Doc Comment
 *
 * @category Class
 * @package  ShopwareSDK6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrderLineItemApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createOrderLineItem
     *
     * Create a new Order Line Item resources.
     *
     */
    public function testCreateOrderLineItem()
    {
    }

    /**
     * Test case for deleteOrderLineItem
     *
     * Delete a Order Line Item resource.
     *
     */
    public function testDeleteOrderLineItem()
    {
    }

    /**
     * Test case for getOrderLineItem
     *
     * Detailed information about a Order Line Item resource.
     *
     */
    public function testGetOrderLineItem()
    {
    }

    /**
     * Test case for getOrderLineItemList
     *
     * List with basic information of Order Line Item resources.
     *
     */
    public function testGetOrderLineItemList()
    {
    }

    /**
     * Test case for updateOrderLineItem
     *
     * Partially update information about a Order Line Item resource.
     *
     */
    public function testUpdateOrderLineItem()
    {
    }
}
