<?php
/**
 * OrderApiTest
 * PHP version 5
 *
 * @category Class
 * @package  ShopwareSDK6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Management API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.15
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace ShopwareSDK6;

use ShopwareSDK6\Configuration;
use ShopwareSDK6\ApiException;
use ShopwareSDK6\ObjectSerializer;

/**
 * OrderApiTest Class Doc Comment
 *
 * @category Class
 * @package  ShopwareSDK6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrderApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createOrder
     *
     * Create a new Order resources.
     *
     */
    public function testCreateOrder()
    {
    }

    /**
     * Test case for deleteOrder
     *
     * Delete a Order resource.
     *
     */
    public function testDeleteOrder()
    {
    }

    /**
     * Test case for getOrder
     *
     * Detailed information about a Order resource.
     *
     */
    public function testGetOrder()
    {
    }

    /**
     * Test case for getOrderList
     *
     * List with basic information of Order resources.
     *
     */
    public function testGetOrderList()
    {
    }

    /**
     * Test case for updateOrder
     *
     * Partially update information about a Order resource.
     *
     */
    public function testUpdateOrder()
    {
    }
}
