<?php
/**
 * ScheduledTaskApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Shopware6SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Management API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.15
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Shopware6SDK;

use Shopware6SDK\Configuration;
use Shopware6SDK\ApiException;
use Shopware6SDK\ObjectSerializer;

/**
 * ScheduledTaskApiTest Class Doc Comment
 *
 * @category Class
 * @package  Shopware6SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ScheduledTaskApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createScheduledTask
     *
     * Create a new Scheduled Task resources.
     *
     */
    public function testCreateScheduledTask()
    {
    }

    /**
     * Test case for deleteScheduledTask
     *
     * Delete a Scheduled Task resource.
     *
     */
    public function testDeleteScheduledTask()
    {
    }

    /**
     * Test case for getScheduledTask
     *
     * Detailed information about a Scheduled Task resource.
     *
     */
    public function testGetScheduledTask()
    {
    }

    /**
     * Test case for getScheduledTaskList
     *
     * List with basic information of Scheduled Task resources.
     *
     */
    public function testGetScheduledTaskList()
    {
    }

    /**
     * Test case for updateScheduledTask
     *
     * Partially update information about a Scheduled Task resource.
     *
     */
    public function testUpdateScheduledTask()
    {
    }
}
