<?php
/**
 * SnippetApiTest
 * PHP version 5
 *
 * @category Class
 * @package  ShopwareSDK6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Management API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.15
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace ShopwareSDK6;

use ShopwareSDK6\Configuration;
use ShopwareSDK6\ApiException;
use ShopwareSDK6\ObjectSerializer;

/**
 * SnippetApiTest Class Doc Comment
 *
 * @category Class
 * @package  ShopwareSDK6
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SnippetApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createSnippet
     *
     * Create a new Snippet resources.
     *
     */
    public function testCreateSnippet()
    {
    }

    /**
     * Test case for deleteSnippet
     *
     * Delete a Snippet resource.
     *
     */
    public function testDeleteSnippet()
    {
    }

    /**
     * Test case for getSnippet
     *
     * Detailed information about a Snippet resource.
     *
     */
    public function testGetSnippet()
    {
    }

    /**
     * Test case for getSnippetList
     *
     * List with basic information of Snippet resources.
     *
     */
    public function testGetSnippetList()
    {
    }

    /**
     * Test case for updateSnippet
     *
     * Partially update information about a Snippet resource.
     *
     */
    public function testUpdateSnippet()
    {
    }
}
